services:
  uav-sim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: uav-tunnel-sim
    entrypoint: ["/entrypoint.sh"]
    command: bash
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./ros2_ws/src/uav_tunnel_gz:/ros2_ws/src/uav_tunnel_gz
      - ./ros2_ws/src/uav_tunnel_nav:/ros2_ws/src/uav_tunnel_nav
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ardupilot_build:/ardu_ws/src/ardupilot/build
    network_mode: host

volumes:
  ardupilot_build:
